#!/bin/sh
# properties = {"type": "single", "rule": "all", "local": true, "input": ["../derivatives/analysis/gradients/sub-CT01/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT02/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT03/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT04/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT06/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT08/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT10/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT11/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT12/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT15/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT16/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT18/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT19/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT20/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-CT22/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD01/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD02/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD03/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD04/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD06/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD07/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD08/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD10/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD11/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD12/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD18/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD19/gradient_image.nii.gz", "../derivatives/analysis/gradients/sub-PD21/gradient_image.nii.gz"], "output": [], "wildcards": {}, "params": {}, "log": [], "threads": 1, "resources": {"mem_mb": 4000}, "jobid": 0, "cluster": {}}
 cd /scratch/dimuthu1/project2/Project_2 && \
/home/dimuthu1/py3/bin/python \
-m snakemake all --snakefile /scratch/dimuthu1/project2/Project_2/Snakefile \
--force -j --keep-target-files --keep-remote \
--wait-for-files /scratch/dimuthu1/project2/Project_2/.snakemake/tmp.k1jlldbv ../derivatives/analysis/gradients/sub-CT01/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT02/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT03/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT04/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT06/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT08/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT10/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT11/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT12/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT15/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT16/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT18/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT19/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT20/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-CT22/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD01/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD02/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD03/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD04/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD06/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD07/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD08/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD10/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD11/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD12/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD18/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD19/gradient_image.nii.gz ../derivatives/analysis/gradients/sub-PD21/gradient_image.nii.gz --latency-wait 5 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules all --nocolor --notemp --no-hooks --nolock \
--mode 2  --use-singularity  --singularity-args "\-e" --use-envmodules --default-resources "mem_mb=4000"  && touch /scratch/dimuthu1/project2/Project_2/.snakemake/tmp.k1jlldbv/0.jobfinished || (touch /scratch/dimuthu1/project2/Project_2/.snakemake/tmp.k1jlldbv/0.jobfailed; exit 1)

